/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;

import base.Main;

	/**
	 *
	 * @author barry
	 */
	public class LoginForm extends javax.swing.JFrame {

	/**
	 * Creates new form LoginForm
	 */
	public LoginForm() {
		setLocationRelativeTo(null);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		userNameField = new javax.swing.JTextField();
		passwordField = new javax.swing.JPasswordField();
		jLabel3 = new javax.swing.JLabel();
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setResizable(false);
		this.setPreferredSize(new Dimension(370, 200));
		getContentPane().setLayout(null);

		jLabel1.setText("Username:");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(70, 60, 52, 14);

		jLabel2.setText("Password:");
		getContentPane().add(jLabel2);
		jLabel2.setBounds(70, 110, 50, 14);

		userNameField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				userNameFieldActionPerformed(evt);
			}
		});
		getContentPane().add(userNameField);
		userNameField.setBounds(160, 60, 150, 25);
		getContentPane().add(passwordField);
		passwordField.setBounds(160, 110, 150, 25);

		jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
		jLabel3.setText("LOGIN");
		getContentPane().add(jLabel3);
		jLabel3.setBounds(150, 10, 70, 30);

		Submit = new JButton();
		Submit.setText("Login");
		getContentPane().add(Submit);
		Submit.setBounds(110, 143, 70, 20);

		
		
		Submit.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				if (LoginConfirmation.checkLogin(userNameField.getText(),
						passwordField.getText().toString())) {
					setVisible(false);
					Main.window.setVisible(true);
				}
			}
		});
		NewAcount = new JButton();
		NewAcount.setText("NewAcount");
		getContentPane().add(NewAcount);
		NewAcount.setBounds(200, 143, 70, 20);

		
		NewAcount.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
					Main.newAccountForm.setVisible(true);
					setVisible(false);
					
				
			}
		});
		pack();
		setVisible(true);
	}// </editor-fold>

	private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPasswordField passwordField;
	private javax.swing.JTextField userNameField;
	public JButton Submit;
	public JButton NewAcount;
	// End of variables declaration
}
