package login;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import base.Main;

import com.firebase.client.Firebase;



/**
 *
 * @author barry
 */
public class NewAccountForm extends javax.swing.JFrame {

	
	private static Firebase fb = new Firebase("https://apcsdnd.firebaseio.com/"); 
	
    /**
     * Creates new form NewAccountForm
     */
    public NewAccountForm() {
    	setLocationRelativeTo(null);
    	this.setPreferredSize(new Dimension(400,300));
    	setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        create = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(username);
        username.setBounds(190, 90, 120, 20);
        getContentPane().add(password);
        password.setBounds(190, 150, 120, 20);

        create.setText("Create New Account");
        getContentPane().add(create);
        create.setBounds(130, 210, 150, 23);

        create.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
					NewAccountCreation.createAccount(username.getText(), password.getText());
				setVisible(false);
				Main.login.setVisible(true);
			}
		});
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 90, 80, 20);

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 150, 60, 20);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel3.setText("Create An Account");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 20, 230, 60);

        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration                   
}
